Fixed IndexError exception
Moved call of getElementsByTagName closer to the place where
result is used.

This will hopefully fix this traceback:

Uncatched Exception:
Traceback (most recent call last):
  File "/usr/bin/build-package", line 395, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/build-package", line 391, in main
    return build(apiurl, tproject, package, timeout)
  File "/usr/bin/build-package", line 329, in build
    error = info.getElementsByTagName('error')[0]
IndexError: list index out of range

Change-Id: Idab6b5a86f74dfecc7cf22c895a97e1f4ccebe61
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>