build-package: Fixed bug in handling empty sproject
Here is the fixed crash:
+ timeout 60m build-package --tproject atm --package blts-alsa-core
packaging/_service

package blts-alsa-core : source project None, target project atm
Uncatched Exception:
Traceback (most recent call last):
  File "/usr/bin/build-package", line 307, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/build-package", line 290, in main
    if exists(apiurl, sproject, package):
  File "/usr/bin/build-package", line 156, in exists
    path_args = [quote_plus(prj)]
  File "/usr/lib64/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable

It's caused by callig 'exists' function with None, when sproject
argument is not passed to build-package.

Change-Id: I98848c4bbcc699b09e52d03e74cbd7541f4082f0
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>