Create package if it doesn't exist
If package doesn't exist in source project there is nothing to branch
and buildpackage fails:
package atm-diverse : source project atm, target project home:tester:Tools-atm-diverse-debug-5305.1
linking project atm to home:tester:Tools-atm-diverse-debug-5305.1
branch package atm/atm-diverse to home:tester:Tools-atm-diverse-debug-5305.1/atm-diverse
Uncatched Exception:
Traceback (most recent call last):
  File "/usr/bin/build-package", line 297, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/build-package", line 286, in main
    branch_package(apiurl, sproject, package, tproject)
  File "/usr/bin/build-package", line 91, in branch_package
    target_package=target_package)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 4560, in branch_pkg
    f = http_POST(u)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2922, in http_POST
    def http_POST(*args, **kwargs):   return http_request('POST', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2909, in http_request
    fd = urllib2.urlopen(req, data=data)
  File "/usr/lib64/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 890, in http_error_401
    url, req, headers)
  File "/usr/lib64/python2.7/urllib2.py", line 865, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib64/python2.7/urllib2.py", line 878, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

This change fixes that. Package is created if it doesn't exist.

Change-Id: I22ba779c3937943eccbf929d691892b18963ec46
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>