Implemented safeosc and used it in shell scripts
This change will hopefully fix job failures caused by osc crashes like this:
+ osc ls -b home:tester:Tools-bmap-tools-68 -r Ubuntu_12.10 -a x86_64
Traceback (most recent call last):
  File "/usr/bin/osc", line 22, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 53, in run
    return prg.main()
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 310, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 333, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 449, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1179, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 357, in do_list
    results.append((repo, get_binarylist(apiurl, project, repo.name, repo.arch, package=package, verbose=opts.verbose)))
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 4730, in get_binarylist
    tree = ET.parse(f)
  File "<string>", line 62, in parse
  File "<string>", line 38, in parse
cElementTree.ParseError: no element found: line 1, column 0
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Note for packager: this script should be put to $PATH (/usr/bin) to be able
to call it from shell scripts

Change-Id: I1554dea6e8073ea236137eee9efc4453ede069ec
Signed-off-by: Ed Bartosh <eduard.bartosh@intel.com>